# Generated by Django 5.2.3 on 2025-06-29 23:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clientes', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('DIAGNOSTICO', 'En Diagnóstico'), ('PRESUPUESTO', 'Presupuesto Enviado'), ('APROBADO', 'Aprobado'), ('EN_TRABAJO', 'En Trabajo'), ('FINALIZADO', 'Finalizado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('kilometraje_ingreso', models.PositiveIntegerField()),
                ('descripcion_falla', models.TextField()),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('trabajos_realizados', models.TextField(blank=True, default='')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('notas_internas', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='clientes.cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='vehiculos.vehiculo')),
            ],
        ),
    ]
