# Generated by Django 5.2.3 on 2025-06-29 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ELEVADOR', 'Elevador'), ('FOSA', 'Fosa'), ('PATIO', 'Patio')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('AUTO', 'Automóvil'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión'), ('MOTO', 'Motocicleta')], default='AUTO', max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('tipo_combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel'), ('GAS', 'Gas')], default='GASOLINA', max_length=20)),
                ('tipo_transmision', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática')], default='MANUAL', max_length=20)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser')),
                ('espacio_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.espaciotaller')),
            ],
        ),
    ]
